version: "3.8"

services:
    api:
        build:
            context: ./.docker
        image: werewolf-api:dev-latest
        user: root
        volumes:
            - ./:/var/www/html
        networks:
            - postgres-network
            # - redis-network
        depends_on:
            postgres:
                condition: service_healthy
            # - redis
        restart: unless-stopped

    postgres:
        image: postgres:14.1-alpine3.15
        environment:
            - POSTGRES_DB=ww_db_test
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - postgres-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    # redis:
    #     image: redis:6.2.5-alpine3.14
    #     environment:
    #         - REDIS_PASSWORD=${REDIS_PASSWORD}
    #     command: redis-server --requirepass ${REDIS_PASSWORD}
    #     networks:
    #         - redis-network
    #     restart: unless-stopped

networks:
    postgres-network:
    # redis-network:
