version: "3.8"

services:
    api:
        build:
            context: ./.docker
        image: werewolf-api:latest
        volumes:
            - ./:/var/www/html
        restart: unless-stopped
        networks:
            - webserver-network
            - postgres-network
        depends_on:
            - postgres

    webserver:
        image: nginx:1.21.3-alpine
        working_dir: /var/www/html
        volumes:
            - ./public:/var/www/html/public
            - ./.docker/nginx/log:/var/log/nginx
            - ./.docker/nginx/ssl:/etc/nginx/ssl
            - ./.docker/nginx/conf:/etc/nginx/conf.d
            - ./.docker/nginx/entrypoint.sh:/docker-entrypoint.d/entrypoint.sh
        ports:
            - 8080:80
            - 443:443
        restart: unless-stopped
        networks:
            - webserver-network
        depends_on:
            - api

    postgres:
        image: postgres:14.1-alpine3.15
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./.docker/postgres/data:/var/lib/postgresql/data
        restart: unless-stopped
        networks:
            - postgres-network

    phppgadmin:
        image: bitnami/phppgadmin:7.13.0
        environment:
            - DATABASE_HOST=${DB_HOST}
            - DATABASE_PORT_NUMBER=${DB_PORT}
        ports:
            - 8081:8080
            - 8443:8443
        restart: unless-stopped
        networks:
            - postgres-network
        depends_on:
            - postgres

networks:
    webserver-network:
    postgres-network:
