name: CICD

on:
  push:
    branches:
      - dev
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'

env:
  REGISTRY: ghcr.io
  BRANCH_NAME: ${{ github.ref }}
  IMAGE_NAME: ${{ github.repository }}
  COMMIT_SHA: ${{ github.sha }}
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  php-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Use phplint
        uses: overtrue/phplint@8.0
        with:
          path: .
          options: --exclude=*.log

  unit-test:
    needs:
      - php-lint

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install
        run: composer install

      - name: Create .env file
        run: cp .env.test .env

      - name: Build containers
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Unit test
        run: docker-compose -f docker-compose.test.yml exec -T api php artisan test tests/Unit

  feature-test:
    needs:
      - php-lint

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install
        run: composer install

      - name: Create .env file
        run: cp .env.test .env

      - name: Build containers
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Unit test
        run: docker-compose -f docker-compose.test.yml exec -T api php artisan test tests/Feature

  build-image:
    needs:
      - unit-test
      - feature-test

    if: ${{ github.event_name == 'push' }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create tags
        id: tags
        run: |
          if [ "${{ env.BRANCH_NAME }}" == "refs/heads/dev" ]; then
            echo "::set-output name=value::\
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-latest, \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-${{ env.COMMIT_SHA }}"
          else
            echo "::set-output name=value::\
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,\
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_MESSAGE }}"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.value }}

  deploy-staging:
    needs:
      - build-image

    if: ${{ github.ref == 'refs/heads/dev' }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            set image deployment/api api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-${{ env.COMMIT_SHA }}

  deploy-production:
    needs:
      - build-image

    if: ${{ github.ref == 'refs/heads/master' }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: echo "Not yet"
